"""Statistics pass: every paper number with its n and spread.

Usage: python stats.py [boot=200]   ->  results/TABLES.md

Sources (all pre-existing artifacts, nothing retrained):
  toy scale   results/grid_<gamma>_s<seed>.log, results/beh_<arm>_s<seed>.log
  capacity    results/big_*.pt (centroids, per-rank behavior, packing report)
              results/big_*.ckpt (unembedding rows for the frame spectrum)
Spreads are median [min, max] over seeds. Angular quantiles carry a 95%
cluster bootstrap CI (resampling WORDS with replacement, all their senses
included; same-word pairs and pair copies excluded). Grams run in strict
fp32 (TF32 disabled) per Amendment 2.
"""
import ast
import glob
import math
import re
import sys
from collections import defaultdict

import torch

import harness
from posthoc import BIG, decompose

torch.backends.cuda.matmul.allow_tf32 = False
dev = "cuda" if torch.cuda.is_available() else "cpu"
BOOT = int(dict(kv.split("=") for kv in sys.argv[1:]).get("boot", 1000))
out = []


def emit(s=""):
    out.append(s)


def spread(vals, fmt="{:.3f}"):
    v = sorted(vals)
    med = v[len(v) // 2] if len(v) % 2 else (v[len(v) // 2 - 1] + v[len(v) // 2]) / 2
    if len(v) == 1:
        return fmt.format(v[0]) + " (n=1)"
    return f"{fmt.format(med)} [{fmt.format(v[0])}, {fmt.format(v[-1])}] n={len(v)}"


# ---- toy scale (d=64) from logs ---------------------------------------------
def parse_toy(path):
    t = open(path).read()
    r = dict(acc=float(re.search(r"cont acc ([\d.]+)", t).group(1)),
             interf=float(re.search(r"interference \(resid\): ([\d.]+)", t).group(1)),
             med=float(re.search(r"\[   resid\] median cos ([+-][\d.]+)", t).group(1)),
             pair=ast.literal_eval(re.search(r"rank-pair mean cos: (\{.*\})", t).group(1)),
             rel=ast.literal_eval(re.search(r"reliability by rank: (\{.*\})", t).group(1)))
    m = re.search(r"per-rank behavior: (\{.*\})", t)
    if m:
        br = ast.literal_eval(m.group(1))
        r["by_rank"] = {k: dict(kv.split("=") for kv in v.split()) for k, v in br.items()}
    return r


toy = defaultdict(list)
for p in glob.glob("results/grid_*_s*.log"):
    g = re.search(r"grid_([\d.]+)_s(\d)", p).group(1)
    toy[("gamma", float(g))].append(parse_toy(p))
beh = defaultdict(list)
for p in glob.glob("results/beh_*_s*.log"):
    knob, val = re.search(r"beh_(gamma|lam)=([\d.]+)_s", p).groups()
    beh[(knob, float(val))].append(parse_toy(p))

emit("# Paper tables with spreads — generated by `stats.py`")
emit()
emit("Format: median [min, max] n=seeds. Toy arm d=64, 2500 steps, k=4 "
     "(regular simplex −0.333). Capacity arm d=4096, 6000 steps, k=5 "
     "(regular simplex −0.25).")
emit()
emit("## T1. Toy arm: weight decay γ (grid runs)")
emit()
emit("| γ | held-out acc | interference | resid median cos | r3-r4 mean cos | other-pairs mean cos | r3-r4 least-negative | min reliability |")
emit("|---|---|---|---|---|---|---|---|")
for (_, g), runs in sorted(toy.items()):
    r34 = [r["pair"]["r3-r4"] for r in runs]
    oth = [sum(v for k, v in r["pair"].items() if k != "r3-r4") / 5 for r in runs]
    top = sum(max(r["pair"], key=r["pair"].get) == "r3-r4" for r in runs)
    rel = [min(r["rel"].values()) for r in runs]
    emit(f"| {g} | {spread([r['acc'] for r in runs])} | {spread([r['interf'] for r in runs])} | "
         f"{spread([r['med'] for r in runs], '{:+.3f}')} | {spread(r34, '{:+.3f}')} | "
         f"{spread(oth, '{:+.3f}')} | {top}/{len(runs)} | {spread(rel)} |")
emit()
emit("## T2. Toy arm: behavioral endpoint, γ vs λ (beh runs)")
emit()
emit("| arm | acc | interference | r1 loss | r3 acc | r4 acc | r4 loss | r3-r4 cos | other pairs cos | r3-r4 − others | r3-r4 least-neg |")
emit("|---|---|---|---|---|---|---|---|---|---|---|")
for (knob, val), runs in sorted(beh.items()):
    br = [r["by_rank"] for r in runs]
    f = lambda rk, key: [float(b[rk][key]) for b in br]  # noqa: E731
    r34 = [r["pair"]["r3-r4"] for r in runs]
    oth = [sum(v for k, v in r["pair"].items() if k != "r3-r4") / 5 for r in runs]
    diff = [r["pair"]["r3-r4"] - sum(v for k, v in r["pair"].items() if k != "r3-r4") / 5 for r in runs]
    top = sum(max(r["pair"], key=r["pair"].get) == "r3-r4" for r in runs)
    emit(f"| {knob}={val} | {spread([r['acc'] for r in runs])} | {spread([r['interf'] for r in runs])} | "
         f"{spread(f('r1', 'loss'))} | {spread(f('r3', 'acc'))} | {spread(f('r4', 'acc'))} | "
         f"{spread(f('r4', 'loss'))} | {spread(r34, '{:+.3f}')} | {spread(oth, '{:+.3f}')} | {spread(diff, '{:+.3f}')} | {top}/{len(runs)} |")

# ---- capacity arm from .pt artifacts ----------------------------------------
arts, sweep, mixed = {}, [], []
for p in sorted(glob.glob("results/big_*.pt")):
    d = torch.load(p, weights_only=False)
    c = d["config"]
    c.setdefault("pen", "coact")
    c.setdefault("prec", "fp32")
    if c["lam"] == 0 and c["pen"] != "coact":
        continue  # lam=0 with pen=uniform is the same model; gate artifact
    c.setdefault("pool_by", "rank")
    c.setdefault("d", int(re.search(r"_d(\d+)", p).group(1)) if "_d" in p else 4096)
    c.setdefault("lr", 1e-4)
    d["_name"] = f"s{c['seed']} {c['prec']}"
    if c["d"] != 4096:
        sweep.append(d)
        continue
    if c["pool_by"] != "rank":
        mixed.append(d)
        continue
    arm = f"λ={c['lam']} {c['pen']}" if c["lam"] else "γ=0 λ=0"
    arts.setdefault(arm, []).append(d)

emit()
emit("## T3. Capacity arm: registered endpoints")
emit()
emit("Runs: " + "; ".join(f"{arm}: {', '.join(a['_name'] for a in runs)}" for arm, runs in arts.items()))
emit("The bf16 γ=0 run is the Amendment-5 gate replicate of seed 0 (same seed, "
     "different numerics) and is listed but not counted as an independent seed.")
emit()
emit("| arm | n indep. seeds | held-out acc | same-word median cos | interference | SGD dev p50 (°) | SGD dev p99.9 (°) | SGD max (°) | viol(±4°) SGD / random |")
emit("|---|---|---|---|---|---|---|---|---|")
for arm, runs in arts.items():
    ind = [a for a in runs if a["config"]["prec"] == "fp32"] or runs
    n_ind = len({a["config"]["seed"] for a in ind})
    pk = [a["packing"] for a in runs]
    emit(f"| {arm} | {n_ind} | {spread([a['acc'] for a in runs])} | {spread([a['med'] for a in runs], '{:+.3f}')} | "
         f"{spread([a['interference'] for a in runs], '{:.4f}')} | {spread([p['sgd_dev_deg']['p50.0'] for p in pk], '{:.2f}')} | "
         f"{spread([p['sgd_dev_deg']['p99.9'] for p in pk], '{:.1f}')} | {spread([p['sgd_max_dev'] for p in pk], '{:.1f}')} | "
         f"{spread([p['grid'][0][1] for p in pk])} / {spread([p['grid'][0][2] for p in pk], '{:.4f}')} |")
emit()
emit(f"Matched-random baseline (same n, d; seed-matched): dev p50 "
     f"{spread([a['packing']['rand_dev_deg']['p50.0'] for r in arts.values() for a in r], '{:.2f}')}, "
     f"p99.9 {spread([a['packing']['rand_dev_deg']['p99.9'] for r in arts.values() for a in r], '{:.2f}')}, "
     f"max {spread([a['packing']['rand_max_dev'] for r in arts.values() for a in r], '{:.2f}')}.")
emit()
emit("## T4. Capacity arm: per-rank held-out behavior and split-half reliability")
emit()
emit("| arm | r1 acc | r2 acc | r3 acc | r4 acc | r5 acc | r5 loss | rel r1 | rel r2 | rel r3 | rel r4 | rel r5 |")
emit("|---|---|---|---|---|---|---|---|---|---|---|---|")
for arm, runs in arts.items():
    acc = lambda r: [a["test_rank"][r]["acc"] for a in runs]  # noqa: E731
    rel = lambda r: [a["rank_rel"][r] for a in runs]  # noqa: E731
    emit(f"| {arm} | " + " | ".join(spread(acc(r)) for r in range(1, 6))
         + f" | {spread([a['test_rank'][5]['loss'] for a in runs], '{:.2f}')} | "
         + " | ".join(spread(rel(r), "{:.2f}") for r in range(1, 6)) + " |")
emit()
emit("Held-out n per rank (seed 0): " + ", ".join(
    f"r{r}={arts['γ=0 λ=0'][0]['test_rank'][r]['n']}" for r in range(1, 6))
     + ". Reliability is the honest denominator: r5 centroids rest on ~4 sentences/word.")

# ---- post-hoc decomposition per artifact ------------------------------------
emit()
emit("## T5. Post-hoc decomposition (NOT pre-registered; replicated across all runs)")
emit()
emit("| arm | dev median shared-cue | dev median disjoint | P(dev>21°) shared / disjoint | disjoint p99.9 | co-occurring mean dev vs non |")
emit("|---|---|---|---|---|---|")
dec = {}
for arm, runs in arts.items():
    rs = [decompose(a["cents"], a["config"]["seed"]) for a in runs]
    dec[arm] = rs
    emit(f"| {arm} | {spread([r['shared']['med'] for r in rs], '{:.1f}')} | {spread([r['disjoint']['med'] for r in rs], '{:.2f}')} | "
         f"{spread([r['shared']['p21'] for r in rs])} / {spread([r['disjoint']['p21'] for r in rs], '{:.4f}')} | "
         f"{spread([r['disjoint']['p999'] for r in rs], '{:.1f}')} | "
         f"{spread([r['cooc_mean'] for r in rs], '{:.2f}')} vs {spread([r['noncooc_mean'] for r in rs], '{:.2f}')} |")
r0 = dec["γ=0 λ=0"][0]
emit()
emit(f"Pair counts (seed 0): {r0['n_pairs']:,} cross-word pairs; {r0['n_shared']:,} shared-cue "
     f"({100 * r0['n_shared'] / r0['n_pairs']:.2f}%); {r0['n_cooc']:,} co-occurring.")
emit()
emit("### T5b. Jaccard dose-response (shared-cue pairs; bin = upper edge of cue-set Jaccard)")
emit()
emit("| arm | " + " | ".join(f"≤{b} med (n)" for b in r0["jaccard"]) + " |")
emit("|---|" + "---|" * len(r0["jaccard"]))
for arm, rs in dec.items():
    cells = []
    for b in r0["jaccard"]:
        cells.append(f"{spread([r['jaccard'][b]['med'] for r in rs], '{:.1f}')} (n={rs[0]['jaccard'][b]['n']})")
    emit(f"| {arm} | " + " | ".join(cells) + " |")

# ---- cluster bootstrap on angular quantiles --------------------------------
emit()
emit(f"## T6. Cross-word deviation: nulls and cluster-bootstrap 95% CIs (B={BOOT})")
emit()
emit("Null A: isotropic unit vectors in R^d (the paper's original baseline). Null B: spectrum-matched Gaussian, "
     "N(0, Σ) with Σ the empirical covariance of the protocol centroids, normalized (word labels kept). "
     "d_eff: median deviation of isotropic vectors in PR dimensions, asin(0.6745/√PR). "
     "CIs: percentile bootstrap resampling words (2000 clusters; same-word pairs are excluded so every pair has expected weight 1) and a delete-one-block jackknife (500 blocks of 4 words sharing a cue pool; a block bootstrap over-weights within-block pairs 2× and is not used).")
emit()
emit("| run | PR | p50 (°) [word CI] [block JK CI] | p99.9 (°) [word CI] [block JK CI] | null A p50 / p99.9 | null B p50 / p99.9 / max | d_eff p50 |")
emit("|---|---|---|---|---|---|---|")


def cross_dev(X, wid):
    """Deviation from orthogonality (degrees) of every cross-word pair, ascending,
    with the (i, j) row indices in the same order."""
    G = (X @ X.T).abs().clamp(max=1.0)
    m = (wid[:, None] != wid[None, :]).triu(1)
    v, ij = torch.rad2deg(torch.asin(G[m])), m.nonzero().to(torch.int32)
    del G, m
    order = v.argsort()
    return v[order], ij[order]


def quants(v):
    """(p50, p99.9, max) of an ascending vector."""
    n = len(v)
    return v[int(0.5 * (n - 1))].item(), v[int(0.999 * (n - 1))].item(), v[-1].item()


def ci(vals):
    s = sorted(vals)
    return s[int(0.025 * (len(s) - 1))], s[int(0.975 * (len(s) - 1))]


def spectrum(M):
    """(participation ratio, λ₁ share, top-16 share) of the squared singular
    values of M via the d×d Gram. PR comes from trace and Frobenius norm in
    fp64; the fp32 eigenvalues only feed the top-k shares."""
    G = M.T @ M
    s2 = torch.linalg.eigvalsh(G).flip(0).clamp(min=0)
    pr = G.diagonal().double().sum() ** 2 / (G.double() ** 2).sum()
    return pr.item(), (s2[0] / s2.sum()).item(), (s2[:16].sum() / s2.sum()).item()


def null_b(X, wid, seed):
    Xc = X - X.mean(0)
    L = torch.linalg.cholesky(Xc.T @ Xc / len(Xc) + 1e-6 * torch.eye(X.shape[1], device=dev))
    g = torch.Generator(device=dev).manual_seed(seed)
    Z = torch.nn.functional.normalize(torch.randn(X.shape, generator=g, device=dev) @ L.T + X.mean(0), dim=1)
    return quants(cross_dev(Z, wid)[0])


def boot_ci(v, ij, clusters, seed):
    """Cluster-bootstrap 95% CIs of p50 / p99.9 over words. Resampling words
    with replacement multiplies pair (i, j) by m[w_i]·m[w_j], so each resample
    is a weighted quantile over the fixed sorted pairs, not a new Gram.
    Same-word pairs are excluded, so every pair has expected weight 1."""
    ids, cl = clusters.unique(return_inverse=True)
    ci_, cj_ = cl[ij[:, 0]].to(torch.int32), cl[ij[:, 1]].to(torch.int32)
    ps = torch.tensor([0.5, 0.999], dtype=torch.float64, device=dev)
    gb = torch.Generator(device="cpu").manual_seed(seed)
    qs = []
    for _ in range(BOOT):
        pick = torch.randint(len(ids), (len(ids),), generator=gb)
        mult = torch.bincount(pick, minlength=len(ids)).to(dev, torch.float32)
        cum = (mult[ci_] * mult[cj_]).cumsum(0, dtype=torch.float64)
        qs.append(v[torch.searchsorted(cum, cum[-1] * ps).clamp(max=len(v) - 1)])
    q50, q999 = torch.stack(qs).T.tolist()
    return ci(q50), ci(q999)


def jack_ci(v, ij, clusters):
    """Delete-one-cluster jackknife 95% CIs of p50 / p99.9 over blocks. A block
    bootstrap is biased here: within-block (shared-cue) pairs get weight
    m_b^2 with E = 2 against 1 for cross-block pairs, so the tail quantile is
    pulled toward the shared-cue population. Deleting one block at a time
    never duplicates a pair."""
    ids, cl = clusters.unique(return_inverse=True)
    ci_, cj_ = cl[ij[:, 0]], cl[ij[:, 1]]
    ps = torch.tensor([0.5, 0.999], dtype=torch.float64, device=dev)
    qs = []
    for b in range(len(ids)):
        keep = ((ci_ != b) & (cj_ != b)).to(torch.float64)
        cum = keep.cumsum(0)
        qs.append(v[torch.searchsorted(cum, cum[-1] * ps).clamp(max=len(v) - 1)])
    Q = torch.stack(qs).double()
    n = len(ids)
    se = ((n - 1) / n * ((Q - Q.mean(0)) ** 2).sum(0)).sqrt()
    full = torch.tensor([v[int(0.5 * (len(v) - 1))], v[int(0.999 * (len(v) - 1))]], dtype=torch.float64, device=dev)
    lo, hi = (full - 1.96 * se).tolist(), (full + 1.96 * se).tolist()
    return (lo[0], hi[0]), (lo[1], hi[1])


def dev_row(a, dd):
    keys = sorted(a["cents"])
    X = torch.stack([a["cents"][k] for k in keys]).to(dev)
    wid = torch.tensor([k[0] for k in keys], device=dev)
    rk = torch.tensor([k[1] for k in keys], device=dev)
    blk = (wid * a["config"]["k"] + rk - 1) % a["config"]["n_blocks"]
    seed = a["config"]["seed"]
    g = torch.Generator().manual_seed(seed)
    R = torch.nn.functional.normalize(torch.randn(len(keys), dd, generator=g), dim=-1).to(dev)
    r50, r999, _ = quants(cross_dev(R, torch.arange(len(keys), device=dev))[0])
    del R
    v, ij = cross_dev(X, wid)
    p50, p999, pmax = quants(v)
    P = spectrum(X - X.mean(0))[0]
    w50, w999 = boot_ci(v, ij, wid, 1000 + seed)
    k50, k999 = jack_ci(v, ij, blk)
    del v, ij
    b50, b999, bmax = null_b(X, wid, 3000 + seed)
    deff = math.degrees(math.asin(0.6745 / math.sqrt(P)))
    return dict(P=P, p50=p50, p999=p999, pmax=pmax, r50=r50, r999=r999, w50=w50, w999=w999, k50=k50, k999=k999,
                b50=b50, b999=b999, bmax=bmax, deff=deff)


def fmt_dev(name, r):
    return (f"| {name} | {r['P']:.0f} | {r['p50']:.2f} [{r['w50'][0]:.2f}, {r['w50'][1]:.2f}] [{r['k50'][0]:.2f}, {r['k50'][1]:.2f}] | "
            f"{r['p999']:.1f} [{r['w999'][0]:.1f}, {r['w999'][1]:.1f}] [{r['k999'][0]:.1f}, {r['k999'][1]:.1f}] | "
            f"{r['r50']:.2f} / {r['r999']:.2f} | {r['b50']:.2f} / {r['b999']:.1f} / {r['bmax']:.1f} | {r['deff']:.2f} |")


devrows = {}
for arm, runs in arts.items():
    for a in runs:
        r = dev_row(a, 4096)
        devrows[(arm, a["_name"])] = r
        emit(fmt_dev(f"{arm} {a['_name']}", r))
emit()
emit("Ratios to null A at p50 / p99.9: " + "; ".join(f"{k[0]} {k[1]}: {r['p50'] / r['r50']:.1f}× / {r['p999'] / r['r999']:.1f}×" for k, r in devrows.items()) + ".")
emit("Ratios to null B at p50 / p99.9 / max: " + "; ".join(f"{k[0]} {k[1]}: {r['p50'] / r['b50']:.2f}× / {r['p999'] / r['b999']:.1f}× / {r['pmax'] / r['bmax']:.1f}×" for k, r in devrows.items()) + ".")

# ---- T9 width sweep ------------------------------------------------------------
emit()
emit("## T9. Width sweep (γ=0, bf16, same corpus and steps; d=512–2048 seed 0 registered 2026-09-02; d=64–256 seeds 0–2 registered 2026-09-05)")
emit()
emit("Rule (registered 2026-09-05): A = spread, PR/d ≥ 0.25; C = drop, r5 acc ≤ 0.13 while r1 within 0.05 of d=4096; else B = squash. "
     "shared / disjoint: median cross-word deviation of shared-cue vs cue-disjoint pairs (posthoc.decompose).")
emit()
emit("| d | seed | lr | acc | r1 acc | r5 acc | r5 loss | PR | PR/d | p50 | p99.9 | null A p50 | null B p50 / p99.9 / max | shared / disjoint med | regime |")
emit("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
base = [a for a in arts.get("γ=0 λ=0", []) if a["config"]["seed"] == 0 and a["config"]["prec"] == "bf16"]
r1_ref = base[0]["test_rank"][1]["acc"] if base else float("nan")
for a in sorted(sweep + base, key=lambda a: (a["config"]["d"], a["config"]["lr"], a["config"]["seed"])):
    d_, c = a["config"]["d"], a["config"]
    r = dev_row(a, d_)
    dc = decompose(a["cents"], c["seed"])
    r1, r5 = a["test_rank"][1]["acc"], a["test_rank"][5]["acc"]
    regime = "A" if r["P"] / d_ >= 0.25 else ("C" if r5 <= 0.13 and r1 >= r1_ref - 0.05 else "B")
    emit(f"| {d_} | {c['seed']} | {c['lr']:g} | {a['acc']:.3f} | {r1:.3f} | {r5:.3f} | {a['test_rank'][5]['loss']:.2f} | "
         f"{r['P']:.0f} | {r['P'] / d_:.3f} | {r['p50']:.2f} | {r['p999']:.1f} | {r['r50']:.2f} | {r['b50']:.2f} / {r['b999']:.1f} / {r['bmax']:.1f} | "
         f"{dc['shared']['med']:.1f} / {dc['disjoint']['med']:.2f} | {regime} |")

# ---- T10 rank-mixed cue pools ---------------------------------------------------
emit()
emit("## T10. Rank-mixed cue pools (pool_by=group, 499 blocks; γ=0, bf16; registered 2026-09-02)")
emit()
emit("| seed | acc | r1 / r5 acc | same-word med cos | PR | p50 | p99.9 | max | null B p50 / p99.9 / max | shared-cue med | disjoint med | P(dev>21°) shared / disjoint | n shared pairs |")
emit("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
for a in sorted(mixed, key=lambda a: a["config"]["seed"]):
    r = dev_row(a, 4096)
    c = a["config"]
    dc = decompose(a["cents"], c["seed"], n_blocks=c["n_blocks"], pool_by=c["pool_by"])
    emit(f"| {c['seed']} | {a['acc']:.3f} | {a['test_rank'][1]['acc']:.3f} / {a['test_rank'][5]['acc']:.3f} | {a['med']:+.3f} | {r['P']:.0f} | "
         f"{r['p50']:.2f} | {r['p999']:.1f} | {a['packing']['sgd_max_dev']:.1f} | {r['b50']:.2f} / {r['b999']:.1f} / {r['bmax']:.1f} | "
         f"{dc['shared']['med']:.1f} | {dc['disjoint']['med']:.2f} | {dc['shared']['p21']:.3f} / {dc['disjoint']['p21']:.4f} | {dc['n_shared']:,} |")

# ---- frame-operator spectrum (Ivanov et al. 2026) ---------------------------
emit()
emit("## T7. Frame-operator spectrum of the unembedding rows for the 10,000 sense tokens")
emit()
emit("F = WᵀW on the sense rows of `unemb` (and on the centered sense centroids). "
     "Participation ratio PR = (Σλ)²/Σλ² is the effective number of occupied "
     "dimensions; a tight frame has PR = d = 4096. Gaussian reference: same "
     "shape, iid entries.")
emit()
emit("| run | unemb PR | unemb λ₁ share | unemb top-16 share | centroid PR | centroid λ₁ share | centroid top-16 share | Gaussian PR |")
emit("|---|---|---|---|---|---|---|---|")


gpr = None
for arm, runs in arts.items():
    for a in runs:
        c = a["config"]
        sfx = ("" if c["prec"] == "fp32" else f"_{c['prec']}") + ("" if c["pen"] == "coact" else f"_{c['pen']}")
        path = f"results/big_g{c['gamma']}_l{c['lam']}_s{c['seed']}{sfx}.ckpt"
        keys = sorted(a["cents"])
        C = torch.stack([a["cents"][k] for k in keys]).to(dev)
        cpr, c1, c16 = spectrum(C - C.mean(0))
        try:
            sd = torch.load(path, map_location="cpu", weights_only=False)
        except FileNotFoundError:
            emit(f"| {arm} {a['_name']} | (no ckpt) | | | {cpr:.0f} | {100 * c1:.1f}% | {100 * c16:.1f}% | |")
            continue
        _, _, meta, _ = harness.prepare(seed=c["seed"], **BIG)
        ids = torch.tensor([t for t, s in meta["cont_id"].items()])
        W = sd["unemb.weight"][ids].to(dev)
        upr, u1, u16 = spectrum(W - W.mean(0))
        if gpr is None:
            gpr = spectrum(torch.randn(W.shape, generator=torch.Generator().manual_seed(0)).to(dev))[0]
        emit(f"| {arm} {a['_name']} | {upr:.0f} | {100 * u1:.1f}% | {100 * u16:.1f}% | {cpr:.0f} | {100 * c1:.1f}% | {100 * c16:.1f}% | {gpr:.0f} |")
        del W, sd

# ---- pre-registration ledger -------------------------------------------------
emit()
emit("## T8. Pre-registration ledger (date each item was written down)")
emit()
emit("| item | registered | outcome |")
emit("|---|---|---|")
for row in [
    ("Toy protocol: decision rule (±0.15), per-word centering, ≥5 seeds, no LN, untied emb", "2026-08-22", "held throughout"),
    ("Arm-5 design: corpus, d=4096, endpoints 1–4, ε-grid, matched-random baseline", "2026-08-22", "run as registered (lr amended, see next)"),
    ("Amendment 1: lr 1e-3 → 1e-4 after 300-step divergence probes", "2026-08-22", "before any full run"),
    ("Amendment 2: TF32 for training/capture; strict-fp32 grams", "2026-08-23", "before any full run"),
    ("Amendment 3: chunked CE + checkpointing + fused AdamW (8GB fit)", "2026-08-23", "verified loss/grad rel-delta 7.7e-8 / 2.8e-7"),
    ("Amendment 4: head gather, drop checkpointing", "2026-08-24", "bitwise on gradient fingerprint; reanalysis bitwise"),
    ("Amendment 5: bf16 autocast, two gates + fp32 penalty stats", "2026-08-24", "gates passed (reliability within 0.006 per rank)"),
    ("Amendment 6: pad skipping", "2026-09-02", "loss/resid bitwise; reanalysis reproduces seed-0 artifact"),
    ("Capture deviation: geometry on full corpus, behavior held-out", "2026-08-23", "stated in Methods"),
    ("λ arm at capacity (coact pricing)", "2026-08-23", "−35% interference (medians), acc within seed spread; shared-cue median 55.4 → 53.6, tail not removed"),
    ("Uniform-pricing fork: 'unpriced' vs 'load-bearing' criterion", "2026-08-24", "alignment survives → load-bearing by criterion"),
    ("Readout ablation P1–P3 (`ablate.py` header)", "2026-08-24", "P1, P3 confirmed; P2 split"),
    ("Check #1 fairness controls + PASS/FAIL/PARTIAL rule (`ablate.py` header)", "2026-09-02", "FAIL: rank k1 ≡ shared k1 (cos ≥ 0.999) in 5/5; 'dedicated channel' retracted"),
    ("Post-hoc (NOT registered): shared-cue / co-occurrence decomposition, Jaccard dose-response", "2026-08-23", "replicated across 4 γ=0 seeds and 3 λ runs"),
    ("Post-hoc (NOT registered): centering identity, spectrum-matched null B, init baseline (`nulls.py`)", "2026-09-02", "−0.25 is the estimator's identity (init −0.249); bulk of deviation = PR≈50 dimensionality; tail 2× null B at p99.9"),
    ("Width sweep d∈{512,1024,2048}, γ=0 s0 bf16 (T9)", "2026-09-02", "acc 0.72→0.91, PR 13→50 with d; p50 tracks null B at every d; tail p99.9 55–58° d-invariant"),
    ("Rank-mixed cue pools, 3 seeds (T10) + two-part decision rule", "2026-09-02", "part (a) met: alignment survives (shared 50° vs disjoint 4.8°, P(>21°) 1.000 vs 0.003); part (b) FAILED (cos 1.000) and was re-scored post hoc as not separable by construction (pair-mean PCA puts the frequency axis first); rule as registered: not passed"),
    ("Low-width sweep d∈{64,128,256}, 3 seeds, predictions A/B/C + lr caveat", "2026-09-05", "none of A/B/C: model squashes and succeeds (acc 0.87–0.93, PR/d 0.06–0.13); lr caveat fired for all three widths, reruns at 1e-3 count"),
    ("Rival hypotheses H1–H4 for PR growth with width; split-half signal PR + lr-confound tests", "2026-09-05", "H1 stands (signal PR 7→42, 5.7×); H2 noise rejected as main cause (11–32% of trace); H3 confirmed: accuracy trend was lr, flat ~0.9 at best-of-lr from d=128; 'capacity is binding' withdrawn"),
    ("Post-hoc (NOT registered): shared-cue alignment on the untrained model (`nulls.py`, 2nd review round)", "2026-09-05", "present at init: shared 17° vs disjoint 1.6° (10×), Jaccard-graded 8→21°; trained 54° vs 5.6° (10×). Alignment is inherited from the cue embeddings and scaled by compression (PR 383→48), not built by SGD; same-rank +5° over cross-rank at init and after"),
]:
    emit("| " + " | ".join(row) + " |")
emit()
emit("Wording retired by this pass: 'zero behavioral cost' → 'no measurable cost "
     "(within the γ=0 seed spread)'; 'dedicated contextual-disambiguation "
     "channel' → 'shared low-dimensional linear context code'; 'simplex-exact "
     "−0.25' → 'differentiation + uniform rank-pair matrix (−0.25 is the "
     "centering identity)'; '9× less orthogonal than random' → '~50 effective "
     "dimensions; bulk matches the spectrum-matched null, tail is 2× above it'; "
     "'SGD builds a shared context code' → 'the shared-cue alignment is inherited from the input and preserved under compression'; "
     "'width is spent on accuracy / capacity is binding' → 'width is spent on dimensions the task does not need (signal PR 7→42, accuracy flat ~0.9 at best-of-lr)'.")

open("results/TABLES.md", "w").write("\n".join(out) + "\n")
print("\n".join(out))
